name: Test Case
on:
  push:
    branches:
      - master
      - alpha
      - beta

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:
      Address: ${{ secrets.ACCOUNT_ADDRESS }}
      PrivateKey: ${{ secrets.ACCOUNT_PRIVATEKEY }}

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: ./.github/actions/ci-setup

      - name: Build
        run: pnpm -F "@node-real/**" build

      - name: Run Test
        run: pnpm -F "@node-real/web3.js-plugin-bundle" test
